controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre?}/{apellidos?}
    controller: App\Controller\HomeController::animales
    defaults: { nombre: 'Kevin Alexander', apellidos: 'Tellez Guerrero'}
    methods: [POST, GET]
    requirements:
        nombre: '[a-zA-Z ]+'
        apellidos: '[a-zA-Z ]+'

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir